CREATE TABLE IF NOT EXISTS mapa_desenhos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(160) NOT NULL,
    tipo VARCHAR(32) NOT NULL DEFAULT 'temporario_dia',
    ferramenta VARCHAR(40) NOT NULL,
    area_tipo VARCHAR(60) NULL,
    geometria_json JSON NOT NULL,
    texto TEXT NULL,
    cor VARCHAR(24) NULL,
    espessura DECIMAL(8,2) NULL,
    opacidade DECIMAL(4,3) NULL,
    preenchimento_cor VARCHAR(24) NULL,
    preenchimento_opacidade DECIMAL(4,3) NULL,
    cor_borda VARCHAR(24) NULL,
    opacidade_borda DECIMAL(4,3) NULL,
    tecnicos_vinculados_json JSON NULL,
    equipe_vinculada VARCHAR(120) NULL,
    data_referencia DATE NULL,
    permanente TINYINT(1) NOT NULL DEFAULT 0,
    visibilidade VARCHAR(32) NOT NULL DEFAULT 'coordenador',
    criado_por VARCHAR(120) NULL,
    atualizado_por VARCHAR(120) NULL,
    removido_por VARCHAR(120) NULL,
    removido_em DATETIME NULL,
    ativo TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_mapa_desenhos_data (ativo, data_referencia, permanente),
    INDEX idx_mapa_desenhos_ferramenta (ativo, ferramenta),
    INDEX idx_mapa_desenhos_visibilidade (visibilidade)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
